/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package svgimport.core;

public class SvgImportGate {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SvgImportGate(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SvgImportGate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        svgimportJNI.delete_SvgImportGate(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static int registerCmds(int mgView) {
    return svgimportJNI.SvgImportGate_registerCmds(mgView);
  }

  public SvgImportGate() {
    this(svgimportJNI.new_SvgImportGate(), true);
  }

}
