/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package svgimport.core;

public class svgimportJNI {
  public final static native int SvgImportGate_registerCmds(int jarg1);
  public final static native long new_SvgImportGate();
  public final static native void delete_SvgImportGate(long jarg1);
}
